name: Irish IPA (phonemizer + eSpeak-NG)

on:
  workflow_dispatch: {}   # Run manually from the Actions tab

permissions:
  contents: write         # So we can commit outputs back to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install system deps (eSpeak-NG)
        run: |
          sudo apt-get update
          sudo apt-get install -y espeak-ng

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install phonemizer pandas

      - name: Transcribe Welsh to IPA with phonemizer (lang=ga)
        run: |
          python - << 'PY'
          import os, csv
          from phonemizer import phonemize

          INP = 'data/irish.txt'
          OUT = 'outputs/irish.csv'
          os.makedirs('outputs', exist_ok=True)

          rows = []
          with open(INP, encoding='utf-8') as f:
            for line in f:
              text = line.strip()
              if not text:
                continue
              ipa = phonemize(
                text,
                language='ga',          # irish
                backend='espeak',       # uses eSpeak-NG installed above
                strip=True,
                njobs=1,
                punctuation_marks=';:,.!?¡¿—…"«»“”()[]{}',
                preserve_punctuation=True,
                with_stress=True
              )
              rows.append((text, ipa))


          with open(OUT, 'w', encoding='utf-8', newline='') as g:
            w = csv.writer(g)
            w.writerow(['text','ipa'])
            w.writerows(rows)

          print(f"Wrote {OUT} with {len(rows)} rows.")
          PY

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: irish-ipa
          path: outputs/irish.csv

      - name: Commit outputs into repo
        uses: EndBug/add-and-commit@v9
        with:
          add: "outputs/irish.csv"
          message: "Add Irish IPA CSV (phonemizer+eSpeak-NG)"
