- name: Transcribe Irish to IPA with phonemizer (lang=ga, cleaned)
  run: |
    python - << 'PY'
    import os, csv
    from phonemizer import phonemize
    from phonemizer.separator import Separator

    INP = 'data/irish.txt'
    OUT = 'outputs/irish.csv'
    os.makedirs('outputs', exist_ok=True)

    SEP = Separator(phone=' ', word=' | ')

    def clean_irish_ipa(ipa: str) -> str:
        ipa = ipa.replace('(ga)', '').replace('(en)', '')
        ipa = ipa.replace('dʒ', 'ɟ')   # optional Irish cleanup
        return ' '.join(ipa.split())

    rows = []
    with open(INP, encoding='utf-8') as f:
        for line in f:
            text = line.strip()
            if not text:
                continue
            ipa = phonemize(
                text,
                language='ga',
                backend='espeak',
                separator=SEP,
                strip=True,
                njobs=1,
                punctuation_marks=';:,.!?¡¿—…"«»“”()[]{}',
                preserve_punctuation=True,
                with_stress=True,
                tie=True,
                language_switch='remove-flags',
                words_mismatch='warn'
            )
            ipa = clean_irish_ipa(ipa)
            rows.append((text, ipa))

    with open(OUT, 'w', encoding='utf-8', newline='') as g:
        w = csv.writer(g)
        w.writerow(['text','ipa'])
        w.writerows(rows)

    print(f"Wrote {OUT} with {len(rows)} rows.")
    PY
