name: Welsh IPA (Epitran)

on:
  workflow_dispatch: {}   # run manually from Actions tab

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install epitran pandas

      - name: Run Welsh transcription
        run: |
          python - << 'PY'
          import epitran, csv, os
          epi = epitran.Epitran('cym-Latn')
          os.makedirs("outputs", exist_ok=True)
          with open("data/welsh.txt", encoding="utf-8") as f, \
               open("outputs/welsh.csv", "w", encoding="utf-8", newline="") as g:
              writer = csv.writer(g)
              writer.writerow(["text", "ipa"])
              for line in f:
                  line = line.strip()
                  if not line: 
                      continue
                  ipa = epi.transliterate(line)
                  writer.writerow([line, ipa])
          PY

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: welsh-ipa
          path: outputs/welsh.csv

      - name: Commit outputs back to repo
        uses: EndBug/add-and-commit@v9
        with:
          add: "outputs/welsh.csv"
          message: "Add Welsh IPA CSV"
