name: Welsh IPA (phonemizer + eSpeak-NG)

on:
  workflow_dispatch: {}   # Run manually from the Actions tab

permissions:
  contents: write         # So we can commit outputs back to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install system deps (eSpeak-NG)
        run: |
          sudo apt-get update
          sudo apt-get install -y espeak-ng

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install phonemizer pandas

      - name: Transcribe Welsh to IPA with phonemizer (lang=cy)
        run: |
          python - << 'PY'
          import os, csv
          from phonemizer import phonemize

          INP = 'data/welsh.txt'
          OUT = 'outputs/welsh.csv'
          os.makedirs('outputs', exist_ok=True)

          rows = []
          with open(INP, encoding='utf-8') as f:
            for line in f:
              text = line.strip()
              if not text:
                continue
              ipa = phonemize(
                text,
                language='cy',          # Welsh
                backend='espeak',       # uses eSpeak-NG installed above
                strip=True,
                njobs=1,
                punctuation_marks=';:,.!?¡¿—…"«»“”()[]{}',
                preserve_punctuation=True,
                with_stress=True
              )
              rows.append((text, ipa))

          # Optional gentle Welsh “polish” (uncomment if desired)
          # def polish(orig, ipa):
          #   w = orig.lower()
          #   # Ensure some common Welsh symbols if they didn't appear
          #   if 'll' in w and 'ɬ' not in ipa:
          #       ipa = ipa.replace('l', 'ɬ', 1)
          #   if w.startswith('rh') and 'r̥' not in ipa:
          #       ipa = ipa.replace('r', 'r̥', 1)
          #   if 'ch' in w and 'x' not in ipa and 'χ' not in ipa:
          #       ipa = ipa.replace('k', 'x', 1) if 'k' in ipa else ipa.replace('h','x',1)
          #   if 'dd' in w and 'ð' not in ipa:
          #       ipa = ipa.replace('d','ð',1)
          #   return ipa
          # rows = [(t, polish(t, i)) for (t, i) in rows]

          with open(OUT, 'w', encoding='utf-8', newline='') as g:
            w = csv.writer(g)
            w.writerow(['text','ipa'])
            w.writerows(rows)

          print(f"Wrote {OUT} with {len(rows)} rows.")
          PY

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: welsh-ipa
          path: outputs/welsh.csv

      - name: Commit outputs into repo
        uses: EndBug/add-and-commit@v9
        with:
          add: "outputs/welsh.csv"
          message: "Add Welsh IPA CSV (phonemizer+eSpeak-NG)"
