name: Welsh IPA (Epitran)

on:
  workflow_dispatch: {}   # lets you run it manually

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install epitran pandas click

      - name: Run Welsh transcription
        run: |
          mkdir -p outputs
          python twisters_cli.py --lang cym-Latn --input data/welsh.txt --output outputs/welsh.csv

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: welsh-ipa
          path: outputs/welsh.csv

      - name: Commit outputs to repo
        uses: EndBug/add-and-commit@v9
        with:
          add: "outputs/welsh.csv"
          message: "Add Welsh IPA CSV"
